# markdownlint configuration
config:
  MD013: false # Line length - impractical for prose and tables
  MD041: false # First line heading - conflicts with VitePress frontmatter
  MD060: false # Table column style - too strict, tables render fine
