packages:
  - packages/*
  - apps/*
  - docs

catalog:
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  ajv: 8.12.0
  json-schema-to-typescript: 15.0.4
  react: 19.2.1
  react-dom: 19.2.1
  typescript: 5.9.3

onlyBuiltDependencies:
  - ' '
  - '"'
  - ','
  - '['
  - ']'
  - a
  - b
  - d
  - e
  - esbuild
  - h
  - i
  - l
  - p
  - r
  - s
  - sharp
  - u
