packages:
  - apps/*
  - packages/*
  - tools/*

allowBuilds:
  bun: true
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
  tree-sitter-cli: true

patchedDependencies:
  outmatch@1.0.0: patches/outmatch@1.0.0.patch
