packages:
  - "packages/*"
  - "apps/*"

# Shared dependency versions - use catalog: in package.json to reference
catalog:
  react: 19.2.1
  react-dom: 19.2.1
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  typescript: 5.9.3
