import type { DesktopEntryList } from "./desktop-source-inventory.js"

const session = "packages/renderer-app/src/session/"

export const rendererInputLists: readonly DesktopEntryList[] = [
  {
    owner: "session native-input freeze",
    file: `${session}session-controller-context.tsx`,
    selector: { kind: "capture" },
    members: [
      "BeforeInput",
      "Input",
      "Change",
      "Click",
      "DoubleClick",
      "ContextMenu",
      "KeyDown",
      "KeyUp",
      "PointerDown",
      "PointerMove",
      "PointerUp",
      "MouseDown",
      "MouseMove",
      "MouseUp",
      "TouchStart",
      "TouchMove",
      "TouchEnd",
      "DragStart",
      "DragOver",
      "Drop",
      "Paste",
      "Cut",
      "CompositionStart",
      "CompositionUpdate",
      "CompositionEnd",
      "Focus",
      "Blur",
      "Submit",
      "Reset",
      "Wheel",
      "Scroll",
    ].map((event) => `on${event}Capture:{admitInput}`),
  },
  {
    owner: "session input admission",
    file: `${session}session-controller-context.tsx`,
    selector: { kind: "calls", within: "admitInput" },
    members: [
      "canAdmitSessionChange",
      "controller.getSnapshot",
      "event.target.closest",
      "control?.getAttribute",
      "selectOperationIsAdmitted",
      "event.preventDefault",
      "event.stopPropagation",
    ],
  },
  {
    owner: "session programmatic mutation admission",
    file: `${session}session-operations.ts`,
    selector: { kind: "calls", within: "change" },
    members: ["canAdmitSessionChange", "this.snapshot", "apply"],
  },
  {
    owner: "session native keyboard admission",
    file: "packages/renderer-app/src/components/App.tsx",
    selector: { kind: "calls", within: "handler" },
    members: [
      "controller.operations.change",
      "e.preventDefault",
      "useUiStore.getState",
      "useUiStore.getState().openSettings",
      "controller.undo",
      "controller.redo",
    ],
  },
]
