// DO NOT EDIT - Generated by scripts/gen-from-schema.ts
// Source: apps/repo-manage/schemas/commands/manifest.json
// To modify the interface, edit the manifest and run `pnpm gen:bindings`

export type ProgressCallback<T> = (message: T) => void

import type {
  AppError,
  AppSettings,
  AssignmentId,
  CloneConfig,
  CommandResult,
  CourseInfo,
  CourseVerifyResult,
  CoverageExportFormat,
  CoverageReport,
  CreateConfig,
  DeleteConfig,
  GenerateFilesParams,
  GetGroupCategoriesParams,
  GitConnection,
  GitIdentityMode,
  GitVerifyResult,
  GroupCategory,
  GroupSelectionMode,
  GroupSelectionPreview,
  GroupSetImportPreview,
  GroupSetImportResult,
  GroupSetSyncResult,
  ImportGitUsernamesResult,
  ImportRosterResult,
  ImportStudentsResult,
  LmsConnection,
  LmsContextKey,
  LmsGroup,
  LmsGroupSet,
  LmsOperationContext,
  LmsType,
  LmsVerifyResult,
  OperationResult,
  PatternFilterResult,
  ProfileSettings,
  RepoOperationContext,
  RepoPreflightResult,
  Result,
  Roster,
  RosterMemberId,
  SettingsLoadResult,
  StudentRemovalCheck,
  SystemGroupSetEnsureResult,
  UsernameVerificationScope,
  ValidationResult,
  VerifyCourseParams,
  VerifyCourseResult,
  VerifyGitUsernamesResult,
} from "./types"

export interface DialogFilter {
  name: string
  extensions: string[]
}

export interface OpenDialogOptions {
  directory?: boolean
  multiple?: boolean
  filters?: DialogFilter[]
  defaultPath?: string
  title?: string
}

export interface SaveDialogOptions {
  defaultPath?: string
  filters?: DialogFilter[]
  title?: string
}

export interface CloseRequestedEvent {
  preventDefault(): void
}

export type CloseRequestedHandler = (
  event: CloseRequestedEvent,
) => void | Promise<void>

export type WindowTheme = "light" | "dark" | "system"

export interface BackendAPI {
  /**
   * Get token generation instructions for an LMS type
   */
  getTokenInstructions(lmsType: string): Promise<Result<string, AppError>>

  /**
   * Open the LMS token generation page in the browser
   */
  openTokenUrl(
    baseUrl: string,
    lmsType: string,
  ): Promise<Result<null, AppError>>

  /**
   * Verify LMS course credentials and fetch course information
   */
  verifyLmsCourse(
    params: VerifyCourseParams,
  ): Promise<Result<VerifyCourseResult, AppError>>

  /**
   * Generate student files from an LMS course
   */
  generateLmsFiles(
    params: GenerateFilesParams,
    progress: ProgressCallback<string>,
  ): Promise<Result<CommandResult, AppError>>

  /**
   * Get group categories (group sets) for a course
   */
  getGroupCategories(
    params: GetGroupCategoriesParams,
  ): Promise<Result<GroupCategory[], AppError>>

  /**
   * Verify LMS connection using app-level LMS connection
   */
  verifyLmsConnection(
    context: LmsOperationContext,
  ): Promise<Result<LmsVerifyResult, AppError>>

  /**
   * Verify draft LMS connection (before saving)
   */
  verifyLmsConnectionDraft(
    context: LmsOperationContext,
  ): Promise<Result<LmsVerifyResult, AppError>>

  /**
   * Fetch courses from LMS (for profile creation)
   */
  fetchLmsCourses(): Promise<Result<CourseInfo[], AppError>>

  /**
   * Fetch courses using draft connection (inline setup)
   */
  fetchLmsCoursesDraft(
    connection: LmsConnection,
  ): Promise<Result<CourseInfo[], AppError>>

  /**
   * Import students from LMS, merge into roster
   */
  importStudentsFromLms(
    context: LmsOperationContext,
    roster: Roster | null,
  ): Promise<Result<ImportStudentsResult, AppError>>

  /**
   * Import students from CSV/Excel file
   */
  importStudentsFromFile(
    profile: string,
    roster: Roster | null,
    filePath: string,
  ): Promise<Result<ImportStudentsResult, AppError>>

  /**
   * Fetch group-set names/ids only (fast)
   */
  fetchLmsGroupSetList(
    context: LmsOperationContext,
  ): Promise<Result<LmsGroupSet[], AppError>>

  /**
   * Fetch groups for a specific group-set
   */
  fetchLmsGroupsForSet(
    context: LmsOperationContext,
    groupSetId: string,
  ): Promise<Result<LmsGroup[], AppError>>

  /**
   * Sync LMS group set: fetch from LMS, update groups in place
   */
  syncGroupSet(
    context: LmsOperationContext,
    roster: Roster,
    groupSetId: string,
  ): Promise<Result<GroupSetSyncResult, AppError>>

  /**
   * Import full roster from LMS (students + staff), merge into existing roster
   */
  importRosterFromLms(
    context: LmsOperationContext,
    roster: Roster | null,
  ): Promise<Result<ImportRosterResult, AppError>>

  /**
   * Create/repair system group sets and normalize group memberships (idempotent)
   */
  ensureSystemGroupSets(
    roster: Roster,
  ): Promise<Result<SystemGroupSetEnsureResult, AppError>>

  /**
   * Normalize a group name using backend slug rules
   */
  normalizeGroupName(name: string): Promise<Result<string, AppError>>

  /**
   * Validate glob and resolve group IDs for assignment preview
   */
  previewGroupSelection(
    roster: Roster,
    groupSetId: string,
    groupSelection: GroupSelectionMode,
  ): Promise<Result<GroupSelectionPreview, AppError>>

  /**
   * Validate glob and return matched value indexes for UI filtering
   */
  filterByPattern(
    pattern: string,
    values: string[],
  ): Promise<Result<PatternFilterResult, AppError>>

  /**
   * Parse CSV for import preview (no persistence)
   */
  previewImportGroupSet(
    roster: Roster,
    filePath: string,
  ): Promise<Result<GroupSetImportPreview, AppError>>

  /**
   * Parse CSV and create new group set
   */
  importGroupSet(
    roster: Roster,
    filePath: string,
  ): Promise<Result<GroupSetImportResult, AppError>>

  /**
   * Re-parse CSV for reimport preview (no persistence)
   */
  previewReimportGroupSet(
    roster: Roster,
    groupSetId: string,
    filePath: string,
  ): Promise<Result<GroupSetImportPreview, AppError>>

  /**
   * Re-parse CSV and update existing group set
   */
  reimportGroupSet(
    roster: Roster,
    groupSetId: string,
    filePath: string,
  ): Promise<Result<GroupSetImportResult, AppError>>

  /**
   * Export group set to CSV file
   */
  exportGroupSet(
    roster: Roster,
    groupSetId: string,
    filePath: string,
  ): Promise<Result<string, AppError>>

  /**
   * Normalize LMS context fields (type, base URL, course)
   */
  normalizeContext(
    lmsType: LmsType,
    baseUrl: string,
    courseId: string,
  ): Promise<Result<LmsContextKey, AppError>>

  /**
   * Verify profile course exists in LMS and return updated name if changed
   */
  verifyProfileCourse(
    profile: string,
  ): Promise<Result<CourseVerifyResult, AppError>>

  /**
   * Verify named git connection
   */
  verifyGitConnection(name: string): Promise<Result<GitVerifyResult, AppError>>

  /**
   * Verify draft git connection (before saving)
   */
  verifyGitConnectionDraft(
    connection: GitConnection,
  ): Promise<Result<GitVerifyResult, AppError>>

  /**
   * List all available profiles
   */
  listProfiles(): Promise<Result<string[], AppError>>

  /**
   * Get the currently active profile
   */
  getActiveProfile(): Promise<Result<string | null, AppError>>

  /**
   * Set the active profile
   */
  setActiveProfile(name: string): Promise<Result<null, AppError>>

  /**
   * Load a profile by name, returning any migration warnings
   */
  loadProfile(name: string): Promise<Result<SettingsLoadResult, AppError>>

  /**
   * Load a profile by name without changing the active profile
   */
  loadProfileSettings(
    name: string,
  ): Promise<Result<SettingsLoadResult, AppError>>

  /**
   * Save profile settings as a named profile (app settings are not touched)
   */
  saveProfile(
    name: string,
    profile: ProfileSettings,
  ): Promise<Result<null, AppError>>

  /**
   * Save profile settings and roster together (atomic)
   */
  saveProfileAndRoster(
    name: string,
    profile: ProfileSettings,
    roster: Roster | null,
  ): Promise<Result<null, AppError>>

  /**
   * Delete a profile by name
   */
  deleteProfile(name: string): Promise<Result<null, AppError>>

  /**
   * Rename a profile
   */
  renameProfile(
    oldName: string,
    newName: string,
  ): Promise<Result<null, AppError>>

  /**
   * Create a new profile with required course binding
   */
  createProfile(
    name: string,
    course: CourseInfo,
  ): Promise<Result<ProfileSettings, AppError>>

  /**
   * Load settings from disk with warnings for any corrected issues
   */
  loadSettings(): Promise<Result<SettingsLoadResult, AppError>>

  /**
   * Load app-level settings (theme, window position, etc.)
   */
  loadAppSettings(): Promise<Result<AppSettings, AppError>>

  /**
   * Save only app-level settings (theme, window position, etc.)
   */
  saveAppSettings(settings: AppSettings): Promise<Result<null, AppError>>

  /**
   * List saved git connection names
   */
  listGitConnections(): Promise<Result<string[], AppError>>

  /**
   * Get a named git connection
   */
  getGitConnection(name: string): Promise<Result<GitConnection, AppError>>

  /**
   * Save a named git connection
   */
  saveGitConnection(
    name: string,
    connection: GitConnection,
  ): Promise<Result<null, AppError>>

  /**
   * Delete a named git connection
   */
  deleteGitConnection(name: string): Promise<Result<null, AppError>>

  /**
   * Get identity mode for a connection name
   */
  getIdentityMode(
    connectionName: string,
  ): Promise<Result<GitIdentityMode, AppError>>

  /**
   * Reset settings to defaults
   */
  resetSettings(): Promise<Result<ProfileSettings, AppError>>

  /**
   * Get default settings (single source of truth from Rust)
   */
  getDefaultSettings(): Promise<ProfileSettings>

  /**
   * Get settings file path
   */
  getSettingsPath(): Promise<Result<string, AppError>>

  /**
   * Check if settings file exists
   */
  settingsExist(): Promise<Result<boolean, AppError>>

  /**
   * Import settings from a specific file
   */
  importSettings(path: string): Promise<Result<ProfileSettings, AppError>>

  /**
   * Export settings to a specific file
   */
  exportSettings(
    settings: ProfileSettings,
    path: string,
  ): Promise<Result<null, AppError>>

  /**
   * Get the JSON schema for ProfileSettings
   */
  getSettingsSchema(): Promise<Result<string, AppError>>

  /**
   * Load settings or return defaults (never fails)
   */
  loadSettingsOrDefault(): Promise<Result<ProfileSettings, AppError>>

  /**
   * Load roster by profile name
   */
  getRoster(profile: string): Promise<Result<Roster | null, AppError>>

  /**
   * Clear roster data for a profile
   */
  clearRoster(profile: string): Promise<Result<null, AppError>>

  /**
   * Check whether a student removal impacts any groups
   */
  checkStudentRemoval(
    profile: string,
    roster: Roster,
    studentId: RosterMemberId,
  ): Promise<Result<StudentRemovalCheck, AppError>>

  /**
   * Import git usernames from CSV
   */
  importGitUsernames(
    profile: string,
    roster: Roster,
    csvPath: string,
  ): Promise<Result<ImportGitUsernamesResult, AppError>>

  /**
   * Verify git usernames exist on platform
   */
  verifyGitUsernames(
    profile: string,
    roster: Roster,
    scope: UsernameVerificationScope,
  ): Promise<Result<VerifyGitUsernamesResult, AppError>>

  /**
   * Export teams to YAML for git operations
   */
  exportTeams(
    profile: string,
    roster: Roster,
    assignmentId: AssignmentId,
    path: string,
  ): Promise<Result<null, AppError>>

  /**
   * Export assignment groups for external editing
   */
  exportGroupsForEdit(
    roster: Roster,
    assignmentId: AssignmentId,
    path: string,
  ): Promise<Result<null, AppError>>

  /**
   * Export all students to CSV/XLSX
   */
  exportStudents(roster: Roster, path: string): Promise<Result<null, AppError>>

  /**
   * Export assignment students with group info
   */
  exportAssignmentStudents(
    roster: Roster,
    assignmentId: AssignmentId,
    path: string,
  ): Promise<Result<null, AppError>>

  /**
   * Get coverage report (student distribution)
   */
  getRosterCoverage(roster: Roster): Promise<Result<CoverageReport, AppError>>

  /**
   * Export coverage report
   */
  exportRosterCoverage(
    roster: Roster,
    path: string,
    format: CoverageExportFormat,
  ): Promise<Result<null, AppError>>

  /**
   * Validate roster (students)
   */
  validateRoster(roster: Roster): Promise<Result<ValidationResult, AppError>>

  /**
   * Validate assignment groups within a roster
   */
  validateAssignment(
    identityMode: GitIdentityMode,
    roster: Roster,
    assignmentId: AssignmentId,
  ): Promise<Result<ValidationResult, AppError>>

  /**
   * Preflight check for create: identifies repos that already exist
   */
  preflightCreateRepos(
    context: RepoOperationContext,
    roster: Roster,
    assignmentId: AssignmentId,
    config: CreateConfig,
  ): Promise<Result<RepoPreflightResult, AppError>>

  /**
   * Preflight check for clone: identifies repos that don't exist
   */
  preflightCloneRepos(
    context: RepoOperationContext,
    roster: Roster,
    assignmentId: AssignmentId,
    config: CloneConfig,
  ): Promise<Result<RepoPreflightResult, AppError>>

  /**
   * Preflight check for delete: identifies repos that don't exist
   */
  preflightDeleteRepos(
    context: RepoOperationContext,
    roster: Roster,
    assignmentId: AssignmentId,
    config: DeleteConfig,
  ): Promise<Result<RepoPreflightResult, AppError>>

  /**
   * Create repos for assignment groups
   */
  createRepos(
    context: RepoOperationContext,
    roster: Roster,
    assignmentId: AssignmentId,
    config: CreateConfig,
  ): Promise<Result<OperationResult, AppError>>

  /**
   * Clone repos for assignment groups
   */
  cloneReposFromRoster(
    context: RepoOperationContext,
    roster: Roster,
    assignmentId: AssignmentId,
    config: CloneConfig,
  ): Promise<Result<OperationResult, AppError>>

  /**
   * Delete repos for assignment groups
   */
  deleteRepos(
    context: RepoOperationContext,
    roster: Roster,
    assignmentId: AssignmentId,
    config: DeleteConfig,
  ): Promise<Result<OperationResult, AppError>>

  /**
   * Open the profiles directory in the system file manager
   */
  revealProfilesDirectory(): Promise<Result<null, AppError>>

  /**
   * Open a file or folder selection dialog.
   */
  openDialog(options: OpenDialogOptions): Promise<string | null>

  /**
   * Open a file save dialog.
   */
  saveDialog(options: SaveDialogOptions): Promise<string | null>

  /**
   * Listen for platform events such as menu actions.
   */
  listenEvent<T = unknown>(
    event: string,
    handler: (payload: T) => void,
  ): Promise<() => void>

  /**
   * Register a handler for window close requests.
   */
  onCloseRequested(handler: CloseRequestedHandler): Promise<() => void>

  /**
   * Programmatically close the current window.
   */
  closeWindow(): Promise<void>

  /**
   * Set the window theme for platform chrome.
   */
  setWindowTheme(theme: WindowTheme): Promise<void>

  /**
   * Set the window background color.
   */
  setWindowBackgroundColor(color: string): Promise<void>
}
