import assert from "node:assert/strict"
import { describe, it } from "node:test"
import type { ExaminationSourceReference } from "@repo-edu/application-contract"
import type { LlmEffort } from "@repo-edu/integrations-llm-contract"
import type { ExaminationDisplaySelection } from "../components/tabs/examination/display-selectors.js"
import { resolveExaminationGenerationPlan } from "../components/tabs/examination/generation-plan.js"
import type { AvailableArchiveEntry } from "../components/tabs/examination/types.js"

function archiveEntry(params: {
  key: string
  questionCount: number
  model: string
  effort: LlmEffort
}): AvailableArchiveEntry {
  const sourceReferences: ExaminationSourceReference[] = [
    {
      sourceId: "E1",
      occurrences: [
        { filePath: "src/example.ts", lineRange: { start: 1, end: 2 } },
      ],
    },
  ]
  return {
    key: params.key,
    questionCount: params.questionCount,
    model: params.model,
    effort: params.effort,
    entry: {
      status: "loaded",
      questions: Array.from({ length: params.questionCount }, (_, index) => ({
        question: `Question ${index + 1}?`,
        answer: `Answer ${index + 1}.`,
        anchor: { sourceId: "E1", lineRange: { start: 1, end: 2 } },
      })),
      usage: null,
      errorMessage: null,
      generatedAt: "2026-01-01T00:00:00.000Z",
      fromArchive: true,
      sourceReferences,
      archivedQuestionCount: params.questionCount,
      archivedModel: params.model,
      archivedEffort: params.effort,
      partialQuestionCount: null,
      generationProgressLabel: null,
      streamedResponseCharacterCount: 0,
      streamedResponsePreview: "",
      inProgressQuestion: null,
      generationControlId: null,
      stopRequested: false,
    },
  }
}

function displayFor(
  entry: AvailableArchiveEntry,
): Pick<ExaminationDisplaySelection, "archiveEntry" | "displayEntry"> {
  return {
    archiveEntry: entry,
    displayEntry: entry.entry,
  }
}

describe("examination generation plan", () => {
  it("starts fresh when the displayed set was generated by another model", () => {
    const displayed = archiveEntry({
      key: "sonnet-8",
      questionCount: 8,
      model: "22",
      effort: "medium",
    })

    const plan = resolveExaminationGenerationPlan({
      display: displayFor(displayed),
      modelCode: "1",
      effort: "none",
      questionCount: 4,
      regenerate: false,
    })

    assert.equal(plan.seedQuestions.length, 0)
    assert.equal(plan.sourceReferences.length, 0)
    assert.equal(plan.requestedQuestionCount, 4)
    assert.equal(plan.additionalQuestionCount, 4)
    assert.equal(plan.targetQuestionCount, 4)
  })

  it("extends the displayed set when its provenance matches the active model", () => {
    const displayed = archiveEntry({
      key: "sonnet-8",
      questionCount: 8,
      model: "22",
      effort: "medium",
    })

    const plan = resolveExaminationGenerationPlan({
      display: displayFor(displayed),
      modelCode: "22",
      effort: "medium",
      questionCount: 4,
      regenerate: false,
    })

    assert.equal(plan.seedQuestions.length, 8)
    assert.equal(plan.sourceReferences, displayed.entry.sourceReferences)
    assert.equal(plan.requestedQuestionCount, 4)
    assert.equal(plan.additionalQuestionCount, 4)
    assert.equal(plan.targetQuestionCount, 12)
  })
})
