// DO NOT EDIT - Generated by scripts/gen-from-schema.ts
// Source: apps/repo-manage/schemas/commands/manifest.json
// To modify commands, edit the manifest and run `pnpm gen:bindings`

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from "@tauri-apps/api/core";
import type { AppError, AppSettings, AssignmentId, CloneParams, CommandResult, ConfigParams, CourseInfo, GenerateFilesParams, GetGroupCategoriesParams, GitConnection, GitIdentityMode, GroupCategory, ProfileSettings, Roster, SettingsLoadResult, SetupParams, StudentId, StudentRemovalCheck, ValidationResult, VerifyCourseParams, VerifyCourseResult, Result } from "./types";

export const commands = {
  /**
   * Get token generation instructions for an LMS type
   */
  async getTokenInstructions(lmsType: string) : Promise<Result<string, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_token_instructions", { lmsType }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Open the LMS token generation page in the browser
   */
  async openTokenUrl(baseUrl: string, lmsType: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("open_token_url", { baseUrl, lmsType }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Verify LMS course credentials and fetch course information
   */
  async verifyLmsCourse(params: VerifyCourseParams) : Promise<Result<VerifyCourseResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("verify_lms_course", { params }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Generate student files from an LMS course
   */
  async generateLmsFiles(params: GenerateFilesParams, progress: TAURI_CHANNEL<string>) : Promise<Result<CommandResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("generate_lms_files", { params, progress }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Get group categories (group sets) for a course
   */
  async getGroupCategories(params: GetGroupCategoriesParams) : Promise<Result<GroupCategory[], AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_group_categories", { params }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Verify platform configuration and authentication
   */
  async verifyConfig(params: ConfigParams) : Promise<Result<CommandResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("verify_config", { params }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Create student repositories from templates
   */
  async setupRepos(params: SetupParams) : Promise<Result<CommandResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("setup_repos", { params }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Clone student repositories (stub for now)
   */
  async cloneRepos(params: CloneParams) : Promise<Result<CommandResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("clone_repos", { params }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * List all available profiles
   */
  async listProfiles() : Promise<Result<string[], AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_profiles") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Get the currently active profile
   */
  async getActiveProfile() : Promise<Result<string | null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_active_profile") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Set the active profile
   */
  async setActiveProfile(name: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("set_active_profile", { name }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Load a profile by name, returning any migration warnings
   */
  async loadProfile(name: string) : Promise<Result<SettingsLoadResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("load_profile", { name }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Save profile settings as a named profile (app settings are not touched)
   */
  async saveProfile(name: string, profile: ProfileSettings) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("save_profile", { name, profile }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Save profile settings and roster together (atomic)
   */
  async saveProfileAndRoster(name: string, profile: ProfileSettings, roster: Roster | null) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("save_profile_and_roster", { name, profile, roster }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Delete a profile by name
   */
  async deleteProfile(name: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("delete_profile", { name }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Rename a profile
   */
  async renameProfile(oldName: string, newName: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("rename_profile", { oldName, newName }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Create a new profile with required course binding
   */
  async createProfile(name: string, course: CourseInfo) : Promise<Result<ProfileSettings, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("create_profile", { name, course }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Load settings from disk with warnings for any corrected issues
   */
  async loadSettings() : Promise<Result<SettingsLoadResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("load_settings") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Load app-level settings (theme, window position, etc.)
   */
  async loadAppSettings() : Promise<Result<AppSettings, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("load_app_settings") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Save only app-level settings (theme, window position, etc.)
   */
  async saveAppSettings(settings: AppSettings) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("save_app_settings", { settings }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * List saved git connection names
   */
  async listGitConnections() : Promise<Result<string[], AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_git_connections") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Get a named git connection
   */
  async getGitConnection(name: string) : Promise<Result<GitConnection, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_git_connection", { name }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Save a named git connection
   */
  async saveGitConnection(name: string, connection: GitConnection) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("save_git_connection", { name, connection }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Delete a named git connection
   */
  async deleteGitConnection(name: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("delete_git_connection", { name }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Get identity mode for a connection name
   */
  async getIdentityMode(connectionName: string) : Promise<Result<GitIdentityMode, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_identity_mode", { connectionName }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Reset settings to defaults
   */
  async resetSettings() : Promise<Result<ProfileSettings, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Get default settings (single source of truth from Rust)
   */
  async getDefaultSettings() : Promise<ProfileSettings> {
    return await TAURI_INVOKE("get_default_settings");
  },
  /**
   * Get settings file path
   */
  async getSettingsPath() : Promise<Result<string, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_settings_path") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Check if settings file exists
   */
  async settingsExist() : Promise<Result<boolean, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("settings_exist") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Import settings from a specific file
   */
  async importSettings(path: string) : Promise<Result<ProfileSettings, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("import_settings", { path }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Export settings to a specific file
   */
  async exportSettings(settings: ProfileSettings, path: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("export_settings", { settings, path }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Get the JSON schema for ProfileSettings
   */
  async getSettingsSchema() : Promise<Result<string, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_settings_schema") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Load settings or return defaults (never fails)
   */
  async loadSettingsOrDefault() : Promise<Result<ProfileSettings, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("load_settings_or_default") };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Load roster by profile name
   */
  async getRoster(profile: string) : Promise<Result<Roster | null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_roster", { profile }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Clear roster data for a profile
   */
  async clearRoster(profile: string) : Promise<Result<null, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("clear_roster", { profile }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Check whether a student removal impacts any groups
   */
  async checkStudentRemoval(profile: string, roster: Roster, studentId: StudentId) : Promise<Result<StudentRemovalCheck, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("check_student_removal", { profile, roster, studentId }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Validate roster (students)
   */
  async validateRoster(roster: Roster) : Promise<Result<ValidationResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("validate_roster", { roster }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  },
  /**
   * Validate assignment groups within a roster
   */
  async validateAssignment(profile: string, roster: Roster, assignmentId: AssignmentId) : Promise<Result<ValidationResult, AppError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("validate_assignment", { profile, roster, assignmentId }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      return { status: "error", error: e as any };
    }
  }
};

