export const SUBMISSION_SELECTION_MAX_FILES = 50
export const SUBMISSION_SELECTION_MAX_BYTES = 512 * 1024

export const EXAMINATION_QUESTION_COUNT_MIN = 1
export const EXAMINATION_QUESTION_COUNT_MAX = 20
